import Navbar from '@/components/Navbar';
import { ReduxProvider } from '@/redux/ReduxProvider';
import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<ReduxProvider>
				<body className='font-nunito max-w-[1760px]'>
					<Navbar />
					{children}
				</body>
			</ReduxProvider>
		</html>
	);
}
